kubeConfigPath: "/Users/z0027kp/.kube/config"
defaultTlsSecret: "kube-system/haproxy-ingress-np-tls-secret"
logLevel: "info"
zone: "central1"
clusters:
  - context: "gcp-central1-bigoli2-test"
    zone: "central1"
  - context: "gcp-east1-bigoli2-test"
    zone: "east1"
  - context: "gcp-central1-bigoli-test"
    zone: "central1"
  - context: "gcp-east1-bigoli-test"
    zone: "east1"