kubeConfigPath: "/Users/z0027kp/.kube/config"
defaultTlsSecret: "kube-system/haproxy-ingress-np-tls-secret"
logLevel: "info"
zone: "tte"
clusters:
  - context: "tgt-tte-bigoli-test"
    zone: "tte"
  - context: "tgt-ttc-bigoli-test"
    zone: "ttc"