#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "envoy-control-plane-helm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "envoy-control-plane-helm.name" . }}
    helm.sh/chart: {{ include "envoy-control-plane-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "envoy-control-plane-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "envoy-control-plane-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Chart.Version }}"
          command:
            - /envoy-control-plane
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: kubeconfig
            mountPath: "/etc"
          - name: config
            mountPath: "/etc"
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{ include "envoy-control-plane-helm.fullname" . }}-kubeconfig
      - name: config
        configMap:
          name: {{ include "envoy-control-plane-helm.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
