apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-control-plane-helm.fullname" . }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: '9901'
  labels:
    app.kubernetes.io/name: {{ include "envoy-control-plane-helm.name" . }}
    helm.sh/chart: {{ include "envoy-control-plane-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9901
      targetPort: admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "envoy-control-plane-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}