controlPlane:
  image: docker.target.com/kubernetes/envoy-control-plane
  pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

envoyproxy:
  image: docker.target.com/kubernetes/envoyproxy
  pullPolicy: Always
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi

fluentd:
  image: docker.target.com/kubernetes/envoyproxy-fluentd
  pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 200Mi

terminationGracePeriod: 305

kubeconfig:
  content: |
    dGVzdAo=
config:
  content: |
    dGVzdAo=

args: []

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
                - envoy-control-plane-helm
        topologyKey: "kubernetes.io/hostname"