replicaCount: 2

image: "docker.target.com/kubernetes/envoy-control-plane"

kubeconfig:
  enabled: true
  content: |
    xxx

args: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
   cpu: 2
   memory: 4Gi
  requests:
   cpu: 1
   memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
