replicaCount: 2

controlPlane:
  image: docker.target.com/kubernetes/envoy-control-plane
  pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

envoyproxy:
  image: docker.target.com/kubernetes/envoyproxy
  pullPolicy: Always
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi

fluentd:
  image: docker.target.com/kubernetes/envoyproxy-fluentd
  pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

kubeconfig:
  content: |
    dGVzdAo=
config:
  content: |
    dGVzdAo=

args: []

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

autoscaler:
  maxReplicas: 10
  minReplicas: 3
  targetCPUUtilizationPercentage: 75