replicaCount: 2

controlPlane:
  image: docker.target.com/kubernetes/envoy-control-plane
  pullPolicy: Always
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi

envoyproxy:
  image: docker.target.com/kubernetes/envoyproxy
  pullPolicy: Always
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi

kubeconfig:
  content: |
    dGVzdAo=
config:
  content: |
    dGVzdAo=

args: []

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

autoscaler:
  maxReplicas: 10
  minReplicas: 3
  targetCPUUtilizationPercentage: 75